name: learn-github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: CI
        run: |
          curl -X POST https://api.github.com/repos/rohithegde/pipeline-workflows/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'